Improve logging for deploy start shell scripts
This commit improves logging during deploy start by:
1. Creating a common module to be sourced by shell scripts to
   load general-use functions, thus reducing code duplication
   between the scripts
2. Replacing plain "echo" commands on the scripts by logging
   functions present on the common module
3. Adding timestamps to the log messages
4. Centralizing all scripts logs into software.log, favouring
   the troubleshooting, now that log lines contain timestamps
   and the process/script that generated them

This commit also deletes the ostree_mounts.yaml file since
it would be used by apt-ostree integration, which was dropped.

Test Plan
PASS: run deploy start successfully and verify that deploy start
      log messages are logged with the expected format

Story: 2010676
Task: 49607

Change-Id: I0bdebde8147faa5b29a642e35bfaf26e9862ed0a
Signed-off-by: Heitor Matsui <heitorvieira.matsui@windriver.com>

diff --git a/software/scripts/deploy-cleanup b/software/scripts/deploy-cleanup
--- a/software/scripts/deploy-cleanup
+++ b/software/scripts/deploy-cleanup
@@ -15,10 +15,14 @@
 # automatic cleanup process fails.
 #
 
-log() {
-  type=$1
-  echo "[$(date --iso-8601=seconds)] $type: $2"
-}
+script_dir=$(dirname $0)
+shell_utils=${script_dir}/shell-utils
+if [ -f $shell_utils ]; then
+    source $shell_utils
+else
+    echo "ERROR: ${shell_utils} module not found."
+    exit 1
+fi
 
 stop_database() {
     local rootdir=$1
@@ -27,7 +31,7 @@ stop_database() {
 
     # attempt to stop temporary database if still up
     tmp_db_dir=${rootdir}/var/lib/postgresql/${to_ver}
-    log "INFO" "Attempting to stop the temporary database in ${tmp_db_dir}..."
+    info "Attempting to stop the temporary database in ${tmp_db_dir}..."
     if [ -d $tmp_db_dir ]; then
         lsof $tmp_db_dir
         if [ $? -eq 0 ]; then
@@ -35,15 +39,15 @@ stop_database() {
             sudo -u postgres ${tmp_db_bin_dir}/pg_ctl -D ${tmp_db_dir} stop
             if [ $? -ne 0 ]; then
                 rc=1
-                log "ERROR" "Error stopping database."
+                error "Error stopping database."
             else
-                log "INFO" "Success stopping database."
+                info "Success stopping database."
             fi
         else
-            log "INFO" "Database is not running."
+            info "Database is not running."
         fi
     else
-        log "WARN" "No database found in the specified directory."
+        warning "No database found in the specified directory."
     fi
     return $rc
 }
@@ -52,20 +56,20 @@ unmount_filesystems() {
     local rootdir=$1
     local rc=0
 
-    log "INFO" "Attempting to unmount filesystems under ${rootdir}..."
+    info "Attempting to unmount filesystems under ${rootdir}..."
     k8s_umount_output=$(sudo umount ${rootdir}/usr/local/kubernetes/current 2>&1)
     if [ $? -ne 0 ]; then
         if [[ ! $k8s_umount_output =~ "not mounted" ]]; then
             rc=1
-            log "ERROR" $k8s_umount_output
+            error $k8s_umount_output
         fi
     fi
     sudo ${rootdir}/usr/sbin/software-deploy/chroot_mounts.sh ${rootdir} -u
     if [ $? -ne 0 ]; then
         rc=1
-        log "ERROR" "Error unmounting filesystems."
+        error "Error unmounting filesystems."
     else
-        log "INFO" "Success unmounting filesystems."
+        info "Success unmounting filesystems."
     fi
     return $rc
 }
@@ -75,14 +79,14 @@ remove_temp_directories() {
     local rootdir=$2
     local rc=0
 
-    log "INFO" "Attempting to remove temporary deployment directories [${repo}, ${rootdir}]..."
+    info "Attempting to remove temporary deployment directories [${repo}, ${rootdir}]..."
     sudo ${rootdir}/usr/sbin/software-deploy/chroot_mounts.sh ${rootdir} -c
     if [ $? -ne 0 ]; then
        rc=1
-       log "ERROR" "Some mount points are still mounted, cannot proceed with the cleanup."
+       error "Some mount points are still mounted, cannot proceed with the cleanup."
     else
         rm -rf $repo $rootdir
-        log "INFO" "Temporary deployment directories removed successfully."
+        info "Temporary deployment directories removed successfully."
     fi
     return $rc
 }
@@ -90,7 +94,7 @@ remove_temp_directories() {
 # script usage
 if [ $# -ne 3 ]; then
     echo
-    echo "usage: deploy-start-cleanup <tmp_ostree_repo_dir> <tmp_root_dir> <action>"
+    echo "usage: deploy-cleanup <tmp_ostree_repo_dir> <tmp_root_dir> <action>"
     echo -e "\nParameters"
     echo "=========="
     echo "tmp_ostree_repo_dir: temporary ostree repo directory (example: /sysroot/upgrade/ostree_repo)"
@@ -111,14 +115,14 @@ action=$3
 # basic checks
 for dir in $repo $rootdir; do
     if [ ! -d $dir ]; then
-        log "ERROR" "Specified directory $dir does not exist, cannot proceed with cleanup."
+        error "Specified directory $dir does not exist, cannot proceed with cleanup."
         exit 1
     fi
 done
 
 target_build_info=${rootdir}/usr/etc/build.info
 if [ ! -f $target_build_info ]; then
-    log "ERROR" "Cannot get target release build-info information, cannot proceed with cleanup."
+    error "Cannot get target release build-info information, cannot proceed with cleanup."
     exit 1
 fi
 
@@ -126,7 +130,7 @@ fi
 to_ver=$(cat $target_build_info | grep SW_VERSION | cut -d'"' -f2)
 
 # main
-log "INFO" "Starting cleanup for staging directories [${repo}, ${rootdir}]..."
+info "Starting cleanup for staging directories [${repo}, ${rootdir}]..."
 case $action in
     "db")
         stop_database $rootdir $to_ver
@@ -143,13 +147,13 @@ case $action in
         remove_temp_directories $repo $rootdir
     ;;
     *)
-        log "ERROR" "Invalid action specified: ${action}"
+        error "Invalid action specified: ${action}"
     ;;
 esac
 rc=$?
 if [ $rc -ne 0 ]; then
-    log "ERROR" "Error cleaning up [${repo}, ${rootdir}], please check the logs, take manual actions and retry the script."
+    error "Error cleaning up [${repo}, ${rootdir}], please check the logs, take manual actions and retry the script."
 fi
-log "INFO" "Cleanup script ended."
+info "Cleanup script ended."
 
 exit $rc
diff --git a/software/scripts/software-deploy-start b/software/scripts/software-deploy-start
--- a/software/scripts/software-deploy-start
+++ b/software/scripts/software-deploy-start
@@ -13,10 +13,17 @@
 # 5. perform data migration
 #
 
-# TODO: centralize USM upgrade scripts output into one single log
-exec > /var/log/deploy_start.log 2>&1
+exec 2>&1 >> /var/log/software.log
 
-exec_path=$(dirname $0)
+script_dir=$(dirname $0)
+shell_utils=${script_dir}/shell-utils
+if [ -f $shell_utils ]; then
+    source $shell_utils
+else
+    echo "ERROR: ${shell_utils} module not found."
+    exit 1
+fi
+
 usage()
 {
     echo "usage: $0 from_ver to_ver k8s_ver postgresql_port feed [commit_id|latest_commit]"
@@ -63,10 +70,10 @@ handle_error() {
     local error_message="$2"
     local state="start-failed"
 
-    echo "Error: ${error_message}" >&2
-    echo "Please check the error details and take appropriate action for recovery." >&2
+    error "${error_message}" >&2
+    error "Please check the error details and take appropriate action for recovery." >&2
 
-    echo "Update deploy state ${state}." >&2
+    error "Update deploy state ${state}." >&2
     deploy_update_state ${state}
 
     # cleanup before exiting
@@ -77,13 +84,14 @@ handle_error() {
 
 for dir in $rootdir $repo; do
     if [ -e ${dir} ]; then
-        echo "${dir} already exists. Please ensure to clean up environment to continue." >&2
+        error "${dir} already exists. Please ensure to clean up environment to continue." >&2
         exit 1
     fi
 done
 
 sudo mkdir ${repo} -p
 
+info "Initializing ostree repo..."
 sudo ostree --repo=${repo} init --mode=archive || handle_error $? "Failed to init repo"
 sudo ostree --repo=${repo} remote add ${instbr} ${feed_url} --no-gpg-verify || handle_error $? "Failed to remote add repo"
 sudo ostree --repo=${repo} pull --depth=-1 --mirror ${instbr}:${instbr} || handle_error $? "Failed to pull repo"
@@ -92,23 +100,27 @@ sudo ostree --repo=${repo} pull --depth=-1 --mirror ${instbr}:${instbr} || handl
 if [ -z ${commit_id} ]; then
     # get commit id, only latest for now
     commit_id=$(ostree rev-parse --repo=${repo} ${instbr})
-    echo "latest commit id ${commit_id}"
+    info "Latest commit id ${commit_id}"
     if [ -z "${commit_id}" ]; then
         handle_error 1 "Failed to retrieve commit id"
     fi
 fi
 
-echo "checkout commit id ${commit_id}"
+info "Checkout commit id ${commit_id}"
 
+info "Checking out ostree repo..."
 sudo ostree --repo=${repo} checkout ${commit_id} ${rootdir} || handle_error $? "Failed to checkout ${commit_id}"
 
 # create proper mounts on deploy file system
+info "Creating mount points..."
 sudo ${rootdir}/usr/sbin/software-deploy/chroot_mounts.sh ${rootdir} || handle_error $? "Failed to mount required mount points"
 
 sudo mount --bind ${rootdir}/usr/local/kubernetes/${k8s_ver} ${rootdir}/usr/local/kubernetes/current
 sudo cp /etc/kubernetes/admin.conf ${rootdir}/etc/kubernetes/
+info "Mount points created successfully"
 
-DATA_PREP_SCRIPT="${exec_path}/prep-data-migration"
+info "Preparing for data migration..."
+DATA_PREP_SCRIPT="${script_dir}/prep-data-migration"
 # OS_AUTH_URL, OS_USERNAME, OS_PASSWORD, OS_PROJECT_NAME, OS_USER_DOMAIN_NAME,
 # OS_PROJECT_DOMAIN_NAME, OS_REGION_NAME are in env variables.
 cmd_line=" --rootdir=${rootdir} --from_release=${from_ver} --to_release=${to_ver}"
@@ -118,17 +130,27 @@ cmd_line+=" --project_domain_name=${OS_PROJECT_DOMAIN_NAME} --region_name=${OS_R
 prep_cmd="${DATA_PREP_SCRIPT} ${cmd_line}"
 
 ${prep_cmd} || handle_error $? "Failed to extract data for migration"
+info "Data migration preparations complete."
 
+info "Creating temporary database..."
 sudo chroot ${rootdir} /usr/sbin/software-deploy/create_postgresql_database.sh ${port} || handle_error $? "Failed to start 2nd instance of postgresql"
-sudo chroot ${rootdir} /usr/bin/software-migrate ${from_ver} ${to_ver} ${port} || handle_error $? "Failed to migrate data"
+info "Database creation complete."
 
+info "Starting data migration..."
+sudo chroot ${rootdir} /usr/bin/software-migrate ${from_ver} ${to_ver} ${port} || handle_error $? "Failed to migrate data"
+info "Data migration completed."
+
+info "Syncing feed between controllers..."
 SYNC_CONTROLLERS_SCRIPT="/usr/sbin/software-deploy/sync-controllers-feed"
 sync_controllers_cmd="${SYNC_CONTROLLERS_SCRIPT} ${cmd_line} --feed=${feed}"
 ${sync_controllers_cmd} || handle_error $? "Failed to sync feeds"
+info "Feed sync complete."
 
 state="start-done"
 deploy_update_state $state
-echo "Update deploy state ${state}."
+info "Update deploy state ${state}."
 
 # cleanup after successful data migration
+info "Starting cleanup..."
 deploy_cleanup
+info "Cleanup complete."
