Include missing data migration steps on deploy start
There are additional steps needed to enable "deploy host"
operation for major release upgrades. This commit adds these
additional steps, which are:

1. Create TO release platform config directory, done during
   upgrade-start on legacy upgrade procedure
2. Create TO release rabbitmq directory, done by upgrade
   manifest after controller-1 reinstall on legacy upgrade

The commit also fixes some issues:

1. shell-utils logging functions logging nowhere after
   being sourced by other scripts
2. sync-controllers-feed script was only syncing the
   ostree_repo directory instead of the full feed content
3. major release deployment scripts ran from different
   places, now all scripts are executed from the TO release
   feed directory, or from checked out TO release ostree
   repo in case of chroot
4. change umount command from chroot_mounts to lazy umount

Note: Since the "deploy host" endpoint for major release
deployment is not yet implemented, the test plan will have
test cases that simulate the "deploy host" operation.

Test Plan
PASS: simulate "deploy host" successfully for AIO-SX
PASS: simulate "deploy host" successfully for AIO-DX

Depends-on: https://review.opendev.org/c/starlingx/config/+/913715

Story: 2010676
Task: 49703

Change-Id: Ib6ae49b3590a1e50acb305ac7482e28bcc4de403
Signed-off-by: Heitor Matsui <heitorvieira.matsui@windriver.com>

diff --git a/software/scripts/software-deploy-start b/software/scripts/software-deploy-start
--- a/software/scripts/software-deploy-start
+++ b/software/scripts/software-deploy-start
@@ -13,7 +13,8 @@
 # 5. perform data migration
 #
 
-exec 2>&1 >> /var/log/software.log
+# Used by shell-utils as the log file path
+LOG_FILE="/var/log/software.log"
 
 script_dir=$(dirname $0)
 shell_utils=${script_dir}/shell-utils
@@ -55,7 +56,7 @@ instbr="starlingx"
 report_agent="deploy-start"
 
 deploy_cleanup() {
-    sudo ${rootdir}/usr/sbin/software-deploy/deploy-cleanup ${repo} ${rootdir} all
+    sudo ${script_dir}/deploy-cleanup ${repo} ${rootdir} all
 }
 
 deploy_update_state() {
@@ -70,10 +71,10 @@ handle_error() {
     local error_message="$2"
     local state="start-failed"
 
-    error "${error_message}" >&2
-    error "Please check the error details and take appropriate action for recovery." >&2
+    error "${error_message}"
+    error "Please check the error details and take appropriate action for recovery."
 
-    error "Update deploy state ${state}." >&2
+    error "Update deploy state ${state}."
     deploy_update_state ${state}
 
     # cleanup before exiting
@@ -84,7 +85,7 @@ handle_error() {
 
 for dir in $rootdir $repo; do
     if [ -e ${dir} ]; then
-        error "${dir} already exists. Please ensure to clean up environment to continue." >&2
+        error "${dir} already exists. Please ensure to clean up environment to continue."
         exit 1
     fi
 done
@@ -113,7 +114,7 @@ sudo ostree --repo=${repo} checkout ${commit_id} ${rootdir} || handle_error $? "
 
 # create proper mounts on deploy file system
 info "Creating mount points..."
-sudo ${rootdir}/usr/sbin/software-deploy/chroot_mounts.sh ${rootdir} || handle_error $? "Failed to mount required mount points"
+sudo ${script_dir}/chroot_mounts.sh ${rootdir} || handle_error $? "Failed to mount required mount points"
 
 sudo mount --bind ${rootdir}/usr/local/kubernetes/${k8s_ver} ${rootdir}/usr/local/kubernetes/current
 sudo cp /etc/kubernetes/admin.conf ${rootdir}/etc/kubernetes/
@@ -141,10 +142,15 @@ sudo chroot ${rootdir} /usr/bin/software-migrate ${from_ver} ${to_ver} ${port} |
 info "Data migration completed."
 
 info "Syncing feed between controllers..."
-SYNC_CONTROLLERS_SCRIPT="/usr/sbin/software-deploy/sync-controllers-feed"
-sync_controllers_cmd="${SYNC_CONTROLLERS_SCRIPT} ${cmd_line} --feed=${feed}"
+SYNC_CONTROLLERS_SCRIPT="${script_dir}/sync-controllers-feed"
+sync_controllers_cmd="${SYNC_CONTROLLERS_SCRIPT} ${cmd_line} --feed=$(dirname $feed)"
 ${sync_controllers_cmd} || handle_error $? "Failed to sync feeds"
 info "Feed sync complete."
+
+# TODO(heitormatsui) remove once sysinv upgrade tables are deprecated
+info "Creating ${to_ver} load entry in legacy upgrade table..."
+sudo -u postgres psql -d sysinv -c "insert into loads(id, uuid, state, software_version) values (nextval('loads_id_seq'), 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'available', '${to_ver}');"
+info "Load created successfully."
 
 state="start-done"
 deploy_update_state $state
